function(run expected)
    execute_process(COMMAND "${ADAPTER}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
    if(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "Adapter status ${status}, expected ${expected}: ${out}${err}")
    endif()
endfunction()
run(1)
run(1 "${WORK}/does-not-exist")
execute_process(COMMAND "${PROGRAM}" --list-tests-json -t expected_abort,missing_abort,wrong_abort,abort_with_failure,numeric,adapter_output
    RESULT_VARIABLE status OUTPUT_VARIABLE inventory)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Could not list adapter fixtures")
endif()
file(WRITE "${WORK}/stale-result" "BARO_CTEST_OK\n")
set(ENV{BARO_CTEST_RESULT} "${WORK}/stale-result")
string(JSON count LENGTH "${inventory}" tests)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON id GET "${inventory}" tests ${index} id)
    string(JSON name GET "${inventory}" tests ${index} name)
    if(name MATCHES "expected_abort|numeric")
        run(0 "${PROGRAM}" --test-id "${id}" --ctest)
    else()
        run(1 "${PROGRAM}" --test-id "${id}" --ctest)
    endif()
endforeach()
file(READ "${WORK}/stale-result" stale)
if(NOT stale STREQUAL "BARO_CTEST_OK\n")
    message(FATAL_ERROR "Adapter reused the caller's stale result file")
endif()
file(REMOVE "${WORK}/stale-result")
