function(check expected)
    execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: ${status}\n${out}${err}")
    endif()
    set(output "${out}" PARENT_SCOPE)
endfunction()
check(0 --test "[typed] values & tolerances")
if(NOT output MATCHES "10 total.*10 passed.*0 failed")
    message(FATAL_ERROR "Typed assertions failed: ${output}")
endif()
check(1 -t typed_fail --junit "${WORK}/typed.xml")
foreach(text "-1 == 2" "18446744073709551615 == 0" "1.25 == 2.5" "8 total")
    string(FIND "${output}" "${text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing ${text}: ${output}")
    endif()
endforeach()
file(READ "${WORK}/typed.xml" xml)
if(NOT xml MATCHES "tests=\"1\" failures=\"1\"" OR NOT xml MATCHES "&lt;diagnostics&gt; &amp; &quot;escaping&quot;")
    message(FATAL_ERROR "Bad JUnit: ${xml}")
endif()
check(0 --list-tests --test "[typed] values & tolerances")
string(STRIP "${output}" output)
if(NOT output STREQUAL "[typed] values & tolerances")
    message(FATAL_ERROR "List executed tests or selected wrong tests: ${output}")
endif()
check(1 --test missing)
check(0 --test missing --allow-empty --junit "${WORK}/empty.xml")
check(1 -p 0)
check(1 -p -1)
check(1 -n 2x)
check(1 --test)
check(1 --junit)
check(1 --unknown)
check(1 unexpected)

execute_process(COMMAND "${EMPTY_PROGRAM}" --allow-empty --junit "${WORK}/empty-suite.xml"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT "${status}" STREQUAL "0" OR NOT out MATCHES "0 total.*0 passed.*0 failed")
    message(FATAL_ERROR "Empty suite failed: ${out}${err}")
endif()
check(1 -t "")
check(1 --baro-child 1 --baro-result "${WORK}/invalid-child" --test missing)
