function(check expected)
    execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: ${status}\n${out}${err}")
    endif()
    string(REPLACE "\r\n" "\n" out "${out}")
    set(output "${out}" PARENT_SCOPE)
endfunction()
check(0 --test "[typed] values & tolerances")
if(NOT output MATCHES "10 total.*10 passed.*0 failed")
    message(FATAL_ERROR "Typed assertions failed: ${output}")
endif()
check(1 -t typed_fail --junit "${WORK}/typed.xml")
foreach(text "-1 == 2" "18446744073709551615 == 0" "1.25 == 2.5" "8 total")
    string(FIND "${output}" "${text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing ${text}: ${output}")
    endif()
endforeach()
check(0 -t typed_ops)
if(NOT output MATCHES "18 total.*18 passed.*0 failed")
    message(FATAL_ERROR "Typed operators failed: ${output}")
endif()
check(1 -t typed_ops_fail)
foreach(text "    n + 1 != 4\n==> 4 != 4\n" "    n < -3\n==> 3 < -3\n"
             "    n >= UINT64_MAX\n==> 3 >= 18446744073709551615\n" "    NULL != NULL\n==> "
             "    n / 2.0 > 2.5\n==> 1.5 > 2.5\n" "Require failed:\n    n * 2 <= n\n==> 6 <= 3\n"
             "6 total")
    string(FIND "${output}" "${text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing ${text}: ${output}")
    endif()
endforeach()
file(READ "${WORK}/typed.xml" xml)
if(NOT xml MATCHES "<testsuite [^>]*time=\"[0-9]+\\.[0-9][0-9][0-9]\"" OR
   NOT xml MATCHES "<testcase [^>]*time=\"[0-9]+\\.[0-9][0-9][0-9]\"")
    message(FATAL_ERROR "JUnit durations missing: ${xml}")
endif()
if(NOT xml MATCHES "tests=\"1\" failures=\"1\"" OR NOT xml MATCHES "&lt;diagnostics&gt; &amp; &quot;escaping&quot;")
    message(FATAL_ERROR "Bad JUnit: ${xml}")
endif()
check(0 --list-tests --test "[typed] values & tolerances")
string(STRIP "${output}" output)
if(NOT output STREQUAL "[typed] values & tolerances")
    message(FATAL_ERROR "List executed tests or selected wrong tests: ${output}")
endif()
check(1 --test missing)
# Every rejected argument explains itself on stderr.
function(rejects message)
    execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    string(FIND "${err}" "${message}" found)
    if(NOT "${status}" STREQUAL "1" OR found EQUAL -1)
        message(FATAL_ERROR "${ARGN}: ${status}, expected '${message}'\n${out}${err}")
    endif()
endfunction()
rejects("Missing value for --jobs" --isolate --jobs)
rejects("Missing value for --timeout" --isolate --timeout)
rejects("Missing value for --test-id" --test-id)
rejects("Missing value for --diagnostics" --diagnostics)
rejects("Expected a positive duration such as 10, 10s or 500ms: abc" --isolate --timeout abc)
rejects("Expected a positive duration such as 10, 10s or 500ms: 5m" --isolate --timeout 5m)
rejects("value should be between 1 and" -p 100000)
rejects("value should be between 1 and 2 inclusive" -n 3 -p 2)
foreach(flag -h --help)
    check(0 ${flag})
    if(NOT output MATCHES "Usage: " OR NOT output MATCHES "-h, --help")
        message(FATAL_ERROR "${flag} did not print usage: ${output}")
    endif()
endforeach()
check(0 --test missing --allow-empty --junit "${WORK}/empty.xml")
check(1 -p 0)
check(1 -p -1)
check(1 -n 2x)
check(1 --test)
check(1 --junit)
check(1 --unknown)
check(1 unexpected)

execute_process(COMMAND "${EMPTY_PROGRAM}" --allow-empty --junit "${WORK}/empty-suite.xml"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT "${status}" STREQUAL "0" OR NOT out MATCHES "0 total.*0 passed.*0 failed")
    message(FATAL_ERROR "Empty suite failed: ${out}${err}")
endif()
check(1 -t "")
check(1 --baro-child 1 --baro-result "${WORK}/invalid-child" --test missing)
check(0 --list-tests-json -t discovery)
string(JSON version GET "${output}" version)
string(JSON count LENGTH "${output}" tests)
if(NOT version EQUAL 1 OR NOT count EQUAL 3)
    message(FATAL_ERROR "Invalid discovery inventory: ${output}")
endif()
set(inventory "${output}")
foreach(index RANGE 0 2)
    string(JSON id GET "${inventory}" tests ${index} id)
    string(JSON name GET "${inventory}" tests ${index} name)
    string(JSON file GET "${inventory}" tests ${index} file)
    string(JSON line GET "${inventory}" tests ${index} line)
    string(JSON tag GET "${inventory}" tests ${index} tags 0)
    if(NOT tag STREQUAL "discovery" OR NOT line GREATER 0 OR NOT EXISTS "${file}")
        message(FATAL_ERROR "Invalid source/tag metadata")
    endif()
    if(index EQUAL 1)
        check(1 --test-id "${id}" --diagnostics compiler)
        string(FIND "${output}" "${file}:${line}: error: assertion failed" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Missing clickable diagnostic: ${output}")
        endif()
        check(1 --test-id "${id}" --isolate --diagnostics compiler)
        string(FIND "${output}" "${file}:${line}: error: assertion failed" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Isolated diagnostics lost compiler format: ${output}")
        endif()
    else()
        check(0 --test-id "${id}")
    endif()
    if(NOT output MATCHES "1 total.*[01] passed.*[01] failed")
        message(FATAL_ERROR "ID did not select exactly one test: ${output}")
    endif()
endforeach()
check(0 --list-tests-json --test missing --allow-empty)
string(JSON count LENGTH "${output}" tests)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "Empty discovery is invalid")
endif()
check(1 --test-id 0)
check(1 --test-id 999999)
check(1 --diagnostics unknown)

check(0 --list-tests-json -t expected_abort,missing_abort,wrong_abort,abort_with_failure)
set(inventory "${output}")
string(JSON count LENGTH "${inventory}" tests)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON id GET "${inventory}" tests ${index} id)
    string(JSON name GET "${inventory}" tests ${index} name)
    if(name MATCHES "^\\[expected_abort\\]")
        check(0 --test-id "${id}" --ctest)
    elseif(name MATCHES "wrong_abort")
        # The CTest adapter requires the abort marker, even if code calls exit(0).
        check(0 --test-id "${id}" --ctest)
        if(output MATCHES "BARO_CTEST_EXPECTED_ABORT")
            message(FATAL_ERROR "Premature exit emitted an abort marker")
        endif()
    else()
        check(1 --test-id "${id}" --ctest)
    endif()
endforeach()
check(1 --ctest)
check(1 --ctest --test-id 1 --isolate)

# Selection is one intersection of tag/name/ID filters, preserving registry IDs.
check(0 --list-tests-json -t ",numeric,, numeric,")
string(JSON count LENGTH "${output}" tests)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Repeated/empty tag tokens changed selection: ${output}")
endif()
string(JSON id GET "${output}" tests 0 id)
string(JSON name GET "${output}" tests 0 name)
check(0 --test-id "${id}" --test "${name}" -t numeric --isolate)
check(1 --test-id "${id}" -t nonexistent)
check(1 --list-tests -t "numeric ")
check(1 --list-tests -t " \t")
check(1 --list-tests -t "numeric, ")
check(0 --list-tests-json -t nonexistent -tnumeric)
string(JSON count LENGTH "${output}" tests)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Last tag option no longer wins: ${output}")
endif()
