file(MAKE_DIRECTORY "${WORK}")
set(args -t "${CASE}")
set(expected_status 1)
set(test_total 1)
set(test_failed 1)
set(assert_total 1)
set(assert_failed 1)
set(diagnostic "Check failed:")

if(CASE STREQUAL "numeric")
    set(expected_status 0)
    set(test_failed 0)
    set(assert_total 16)
    set(assert_failed 0)
    set(diagnostic "")
elseif(CASE STREQUAL "float_failure")
    set(diagnostic "1.1 == 1.9")
elseif(CASE STREQUAL "require")
    set(diagnostic "Require failed:")
elseif(CASE STREQUAL "output")
    list(APPEND args -o)
    set(test_total 2)
elseif(CASE STREQUAL "suppression")
    list(APPEND args -e)
    set(expected_status 0)
    set(test_failed 0)
    set(assert_total 0)
    set(assert_failed 0)
    set(diagnostic "")
elseif(CASE STREQUAL "descriptors")
    set(assert_total 101)
    if(NOT WIN32)
        set(assert_total 103)
    endif()
    set(assert_failed 100)
elseif(CASE STREQUAL "many")
    set(test_total 256)
    set(test_failed 256)
    set(assert_total 256)
    set(assert_failed 256)
elseif(CASE STREQUAL "cleanup_failure")
    set(test_total 2)
    set(assert_total 2)
    set(diagnostic "Require failed:")
elseif(CASE STREQUAL "cleanup")
    set(test_total 2)
    set(assert_total 3)
    set(diagnostic "Require failed:")
elseif(CASE STREQUAL "abort")
    list(APPEND args -r)
    set(test_total 3)
    set(test_failed 2)
    set(assert_total 3)
    set(assert_failed 2)
    set(diagnostic "Assertion failed! Caught SIGABRT")
elseif(CASE STREQUAL "null_strings")
    set(expected_status 0)
    set(test_failed 0)
    set(assert_total 8)
    set(assert_failed 0)
    set(diagnostic "")
elseif(CASE STREQUAL "null_failures")
    set(assert_total 4)
    set(assert_failed 4)
    set(diagnostic "Require (case insensitive) failed:")
elseif(CASE MATCHES "^capture([0-9]+)$")
    set(capture_size "${CMAKE_MATCH_1}")
    set(assert_total 2)
    set(assert_failed 2)
elseif(CASE STREQUAL "capture_isolation")
    set(test_total 2)
elseif(CASE STREQUAL "partition")
    set(args -n "${PARTITION}" -p 6)
    if(PARTITION LESS_EQUAL 4)
        set(test_total 2)
        math(EXPR first "2 * (${PARTITION} - 1) + 1")
    else()
        set(test_total 1)
        math(EXPR first "${PARTITION} + 4")
    endif()
    set(test_failed ${test_total})
    set(assert_total ${test_total})
    set(assert_failed ${test_total})
    set(diagnostic "Require failed:")
else()
    message(FATAL_ERROR "Unknown regression case: ${CASE}")
endif()

execute_process(COMMAND "${PROGRAM}" ${args} WORKING_DIRECTORY "${WORK}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
string(REPLACE "\r\n" "\n" output "${output}")
if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "${CASE}: expected exit ${expected_status}, got ${status}\n${output}${error}")
endif()
if(NOT "${error}" STREQUAL "")
    message(FATAL_ERROR "Unexpected stderr: ${error}\n${output}")
endif()
foreach(kind test assert)
    math(EXPR passed "${${kind}_total} - ${${kind}_failed}")
    if(NOT output MATCHES "${kind}s: +${${kind}_total} total \\| +${passed} passed \\| +${${kind}_failed} failed")
        message(FATAL_ERROR "Incorrect ${kind} totals: ${output}")
    endif()
endforeach()
string(FIND "${output}" "${diagnostic}" found)
if(found EQUAL -1)
    message(FATAL_ERROR "Missing diagnostic '${diagnostic}': ${output}")
endif()
if(output MATCHES "UNREACHABLE|HIDDEN_")
    message(FATAL_ERROR "Unexpected output: ${output}")
endif()
if(CASE STREQUAL "output")
    foreach(marker BEFORE_FAILURE AFTER_FAILURE NEXT_TEST)
        if(NOT output MATCHES "${marker}")
            message(FATAL_ERROR "Missing ${marker}: ${output}")
        endif()
    endforeach()
endif()
if(CASE STREQUAL "null_failures")
    string(REGEX MATCHALL "\\[null\\]" nulls "${output}")
    list(LENGTH nulls count)
    if(NOT count EQUAL 5)
        message(FATAL_ERROR "Missing null diagnostics: ${output}")
    endif()
endif()
if(DEFINED capture_size)
    string(REPEAT "ABCDEFGHIJKLMNOPQRSTUVWXYZ" 347 bytes)
    math(EXPR start "${capture_size} - 4096")
    if(start LESS 0)
        set(start 0)
    endif()
    math(EXPR length "${capture_size} - ${start}")
    string(SUBSTRING "${bytes}" ${start} ${length} expected_capture)
    string(FIND "${output}" "Captured output:\n${expected_capture}\n=" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Captured tail does not match exactly: ${output}")
    endif()
    string(FIND "${output}" "Captured output:\nSECOND_SEGMENT\n=" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Capture was not reset between failures: ${output}")
    endif()
endif()
if(CASE STREQUAL "capture_isolation")
    if(output MATCHES "PASS_ONLY" OR NOT output MATCHES "Captured output:\nFAIL_ONLY\n")
        message(FATAL_ERROR "Capture leaked between tests: ${output}")
    endif()
endif()
if(CASE STREQUAL "partition")
    math(EXPR last "${first} + ${test_total} - 1")
    string(FIND "${output}" "(Partition ${PARTITION}: tests ${first} through ${last})" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Incorrect partition bounds: ${output}")
    endif()
    foreach(index RANGE ${first} ${last})
        if(NOT output MATCHES "In: ${index} ")
            message(FATAL_ERROR "Partition skipped test ${index}: ${output}")
        endif()
    endforeach()
endif()
if(NOT WIN32 AND EXISTS "${WORK}/NUL")
    message(FATAL_ERROR "Runner created a NUL file")
endif()
