function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "${ARGV}\n${out}${err}")
    endif()
endfunction()
run("${CMAKE_COMMAND}" --install "${BUILD}" --prefix "${BUILD}/consumer-prefix" --config "${CONFIG}")
foreach(mode source installed)
    if(mode STREQUAL "source")
        set(option "-DBARO_SOURCE=${SOURCE}")
    else()
        set(option "-DCMAKE_PREFIX_PATH=${BUILD}/consumer-prefix")
    endif()
    run("${CMAKE_COMMAND}" -S "${SOURCE}/tests/consumer" -B "${BUILD}/consumer-${mode}" "${option}")
    run("${CMAKE_COMMAND}" --build "${BUILD}/consumer-${mode}" --config "${CONFIG}")
    run("${CMAKE_CTEST_COMMAND}" --test-dir "${BUILD}/consumer-${mode}" -C "${CONFIG}" --output-on-failure)
    execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${BUILD}/consumer-${mode}" -C "${CONFIG}" -V
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${status}" STREQUAL "0" OR NOT out MATCHES "2 total.*2 passed.*0 failed")
        message(FATAL_ERROR "Archive tests were not linked: ${out}${err}")
    endif()
endforeach()
