cmake_minimum_required(VERSION 3.20)
include("${SOURCE}/cmake/Baro.cmake")
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
function(parameters mode)
    set(BARO_EXECUTABLE "${PROBE}")
    set(BARO_RUNNER "${RUNNER}")
    set(BARO_CMAKE_COMMAND "${CMAKE_COMMAND}")
    set(BARO_SOURCE_DIRECTORY "${WORK}/source")
    set(BARO_WORKING_DIRECTORY "${WORK}")
    set(BARO_DISCOVERY_TIMEOUT 1)
    set(BARO_OUTPUT "${WORK}/tests.cmake")
    set(BARO_MANIFEST "${WORK}/inventory.json")
    set(BARO_ENVIRONMENT_COUNT 2)
    set(BARO_ENVIRONMENT_0 "BARO_PROBE_MODE=${mode}")
    set(BARO_ENVIRONMENT_1 "BARO_PROBE_JSON=${WORK}/input.json")
    # An emulator with multiple arguments, spaces, and a literal semicolon.
    set(BARO_EMULATOR_COUNT 4)
    set(BARO_EMULATOR_0 "${CMAKE_COMMAND}")
    set(BARO_EMULATOR_1 -E)
    set(BARO_EMULATOR_2 env)
    set(BARO_EMULATOR_3 "BARO_EMULATOR_CHECK=arg with spaces;and semicolon")
    get_cmake_property(variables VARIABLES)
    set(code "")
    foreach(key IN LISTS variables)
        if(key MATCHES "^BARO_")
            _baro_literal(value "${${key}}")
            string(APPEND code "set(${key} ${value})\n")
        endif()
    endforeach()
    _baro_literal(module "${SOURCE}/cmake/BaroDiscoverTests.cmake")
    file(WRITE "${WORK}/CTestTestfile.cmake" "${code}include(${module})\n")
endfunction()
function(discover expected pattern)
    execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${WORK}" --show-only=json-v1
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10)
    if(expected STREQUAL "PASS")
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "Discovery failed: ${output}${errors}")
        endif()
    elseif("${status}" STREQUAL "0")
        message(FATAL_ERROR "Invalid discovery succeeded: ${output}")
    endif()
    if(NOT "${output}${errors}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing ${pattern}: ${output}${errors}")
    endif()
    set(inventory "${output}" PARENT_SCOPE)
endfunction()
set(test1 "{\"id\":1,\"name\":\"duplicate\",\"file\":\"${WORK}/source/a.c\",\"line\":1,\"expect_abort\":false,\"tags\":[]}")
set(test2 "{\"id\":2,\"name\":\"duplicate\",\"file\":\"${WORK}/source/b.c\",\"line\":1,\"expect_abort\":false,\"tags\":[]}")
set(valid "{\"version\":1,\"tests\":[${test1},${test2}]}")
file(WRITE "${WORK}/input.json" "${valid}")
parameters(ok)
discover(PASS "duplicate")
string(JSON first GET "${inventory}" tests 0 name)
string(JSON second GET "${inventory}" tests 1 name)
if(NOT first STREQUAL "duplicate [a.c]" OR NOT second STREQUAL "duplicate [b.c]")
    message(FATAL_ERROR "Cross-file duplicates are not stable: ${inventory}")
endif()
file(READ "${WORK}/tests.cmake" last_good)
foreach(mode fail crash hang)
    parameters("${mode}")
    discover(FAIL "Baro discovery failed")
endforeach()
parameters(ok)
foreach(invalid "not json" "{\"version\":2,\"tests\":[]}" "{\"version\":1,\"tests\":{}}"
        "{\"version\":1,\"tests\":[${test1},${test1}]}" "{\"version\":1,\"tests\":[{}]}")
    file(WRITE "${WORK}/input.json" "${invalid}")
    discover(FAIL "Baro|baro")
    file(READ "${WORK}/tests.cmake" retained)
    if(NOT retained STREQUAL last_good)
        message(FATAL_ERROR "Failed discovery published a partial inventory")
    endif()
endforeach()
foreach(replacement "\"id\":0" "\"id\":\"1\"" "\"id\":1.5")
    string(REPLACE "\"id\":1" "${replacement}" invalid "${valid}")
    file(WRITE "${WORK}/input.json" "${invalid}")
    discover(FAIL "Invalid Baro")
endforeach()
file(WRITE "${WORK}/input.json" "{\"version\":1,\"tests\":[]}")
discover(PASS "tests")
string(JSON count LENGTH "${inventory}" tests)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "Empty inventory registered tests")
endif()
# Simulate an interrupted writer. Recovery must ignore temporary content.
file(WRITE "${WORK}/tests.cmake.tmp" "broken partial output")
file(WRITE "${WORK}/input.json" "${valid}")
discover(PASS "duplicate")
file(WRITE "${WORK}/quiet.cmake" "execute_process(COMMAND \"${CMAKE_CTEST_COMMAND}\" --test-dir \"${WORK}\" -N RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE errors)\nif(NOT status EQUAL 0)\nmessage(FATAL_ERROR \"\${errors}\")\nendif()\n")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -P "${WORK}/quiet.cmake"
    COMMAND "${CMAKE_COMMAND}" -P "${WORK}/quiet.cmake"
    RESULTS_VARIABLE statuses OUTPUT_QUIET ERROR_VARIABLE errors TIMEOUT 15)
if(NOT statuses STREQUAL "0;0")
    message(FATAL_ERROR "Concurrent discovery failed: ${statuses} ${errors}")
endif()
# Parameter validation runs at configure time and needs a real executable target.
file(MAKE_DIRECTORY "${WORK}/invalid")
foreach(arguments "TIMEOUT -1" "DISCOVERY_TIMEOUT 0" "EXTRA_ARGS --isolate" "PROPERTIES TIMEOUT" "UNKNOWN value")
    file(WRITE "${WORK}/invalid/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(invalid NONE)\ninclude(\"${SOURCE}/cmake/Baro.cmake\")\nadd_executable(probe IMPORTED)\nbaro_discover_tests(probe ${arguments})\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${WORK}/invalid" -B "${WORK}/invalid-build"
        RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE errors)
    if("${status}" STREQUAL "0" OR NOT errors MATCHES "baro_discover_tests")
        message(FATAL_ERROR "Invalid arguments accepted: ${arguments}: ${errors}")
    endif()
endforeach()
