function(run expected)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
    if(expected STREQUAL "FAIL")
        if("${status}" STREQUAL "0")
            message(FATAL_ERROR "Expected failure: ${ARGN}\n${out}${err}")
        endif()
    elseif(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: ${status}\n${out}${err}")
    endif()
    set(output "${out}" PARENT_SCOPE)
    set(errors "${err}" PARENT_SCOPE)
endfunction()
function(inventory expected)
    run(0 "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" --show-only=json-v1)
    string(JSON count LENGTH "${output}" tests)
    if(NOT count EQUAL expected)
        message(FATAL_ERROR "Expected ${expected} tests, got ${count}: ${output}")
    endif()
    set(inventory "${output}" PARENT_SCOPE)
endfunction()
function(property out test name)
    string(JSON count LENGTH "${inventory}" tests ${test} properties)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON key GET "${inventory}" tests ${test} properties ${index} name)
        if(key STREQUAL name)
            string(JSON value GET "${inventory}" tests ${test} properties ${index} value)
            set(${out} "${value}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Missing property ${name}: ${inventory}")
endfunction()
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(COPY "${SOURCE}/tests/discovery_fixture/" DESTINATION "${WORK}/source fixture")
set(binary "${WORK}/binary fixture")
run(0 "${CMAKE_COMMAND}" -S "${WORK}/source fixture" -B "${binary}" -G "${GENERATOR}"
    "-DBARO_SOURCE=${SOURCE}" -DCMAKE_BUILD_TYPE=Debug)
if(MULTI)
    set(configs Debug Release)
else()
    set(configs Debug)
endif()
foreach(config IN LISTS configs)
    # An unbuilt configuration gets an explicit failing placeholder, never a stale executable.
    inventory(1)
    string(JSON placeholder GET "${inventory}" tests 0 name)
    if(NOT placeholder MATCHES "NOT_BUILT")
        message(FATAL_ERROR "Missing unbuilt configuration placeholder: ${placeholder}")
    endif()
    run(0 "${CMAKE_COMMAND}" --build "${binary}" --config "${config}" --parallel 4)
    inventory(18)
    if(config STREQUAL "Debug")
        set(original "${inventory}")
    else()
        foreach(index RANGE 0 17)
            string(JSON previous GET "${original}" tests ${index} name)
            string(JSON current GET "${inventory}" tests ${index} name)
            if(NOT previous STREQUAL current)
                message(FATAL_ERROR "Configuration changed test identity")
            endif()
        endforeach()
    endif()
    file(READ "${binary}/.baro/fixture/${config}.json" metadata)
    foreach(index RANGE 0 17)
        string(JSON id GET "${metadata}" tests ${index} id)
        string(JSON name GET "${metadata}" tests ${index} name)
        string(JSON actual GET "${inventory}" tests ${index} name)
        set(expected "case::${name}::suite")
        if(index LESS 2)
            math(EXPR occurrence "${index} + 1")
            set(expected "case::${name} [cases.c #${occurrence}]::suite")
        endif()
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "CTest changed a test name: ${actual}")
        endif()
        string(JSON command GET "${inventory}" tests ${index} command)
        string(JSON selector GET "${inventory}" tests ${index} command 3)
        if(NOT selector STREQUAL "${id}")
            message(FATAL_ERROR "Incorrect unique selector: ${command}")
        endif()
        if(command MATCHES "--isolate|--jobs|--timeout")
            message(FATAL_ERROR "Nested supervision of ordinary CTest test: ${command}")
        endif()
        property(timeout ${index} TIMEOUT)
        property(processors ${index} PROCESSORS)
        property(lock ${index} RESOURCE_LOCK)
        property(labels ${index} LABELS)
        property(environment ${index} ENVIRONMENT)
        property(directory ${index} WORKING_DIRECTORY)
        if(NOT timeout EQUAL 0.3 OR NOT processors EQUAL 2 OR NOT lock MATCHES "database" OR
           NOT labels MATCHES "explicit;label" OR NOT labels MATCHES "config-${config}" OR
           NOT environment MATCHES "BARO_VALUE=alpha;beta" OR NOT directory STREQUAL "${binary}/working directory")
            message(FATAL_ERROR "Lost CTest properties: ${inventory}")
        endif()
    endforeach()
    # Source metadata remains available independently of IDE-specific adapters.
    string(JSON file GET "${metadata}" tests 1 file)
    string(JSON line GET "${metadata}" tests 1 line)
    run(0 "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^pass$" -j 4 --output-on-failure)
    run(0 "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -R "cases.c #1" --output-on-failure)
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -R "cases.c #2" --output-on-failure)
    string(FIND "${output}" "${file}:${line}: error: assertion failed" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing editor-friendly diagnostic: ${output}")
    endif()
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" --rerun-failed --output-on-failure)
    if(NOT output MATCHES "1/1")
        message(FATAL_ERROR "Rerun-failed did not select just the failed case: ${output}")
    endif()
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^timeout$" --output-on-failure)
    if(NOT output MATCHES "Timeout")
        message(FATAL_ERROR "CTest did not enforce deadline: ${output}")
    endif()
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^expected_timeout$" --output-on-failure)
    if(NOT output MATCHES "Timeout")
        message(FATAL_ERROR "Expected-abort test escaped CTest's timeout: ${output}")
    endif()
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^premature$" --output-on-failure)
    if(NOT output MATCHES "0% tests passed, 4 tests failed out of 4")
        message(FATAL_ERROR "Expected-abort false positive: ${output}")
    endif()
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^completion$" --output-on-failure)
    if(NOT output MATCHES "0% tests passed, 5 tests failed out of 5")
        message(FATAL_ERROR "Premature completion false positive: ${output}")
    endif()
    file(REMOVE "${binary}/descendant-marker" "${binary}/descendant-marker.started")
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^descendant_timeout$" --output-on-failure)
    run(0 "${CMAKE_COMMAND}" -E sleep 2.2)
    if(NOT EXISTS "${binary}/descendant-marker.started" OR EXISTS "${binary}/descendant-marker")
        message(FATAL_ERROR "CTest failed to start/terminate the descendant")
    endif()
    # Concurrent invocations must not share result records.
    string(JSON adapter GET "${inventory}" tests 0 command 0)
    string(JSON executable GET "${inventory}" tests 0 command 1)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "BARO_VALUE=alpha;beta" "${adapter}" "${executable}" --test-id 1 --ctest
        COMMAND "${CMAKE_COMMAND}" -E env "BARO_VALUE=alpha;beta" "${adapter}" "${executable}" --test-id 1 --ctest
        WORKING_DIRECTORY "${binary}/working directory" RESULTS_VARIABLE statuses OUTPUT_QUIET ERROR_VARIABLE adapter_errors)
    if(NOT statuses STREQUAL "0;0")
        message(FATAL_ERROR "Concurrent adapters failed: ${statuses}: ${adapter_errors}")
    endif()
    run(FAIL "${CMAKE_COMMAND}" -E env BARO_MAIN_FAIL=1 "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^context$" --output-on-failure)
    run(FAIL "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C "${config}" -L "^crash$" --output-on-failure)
    if(NOT output MATCHES "signal|process=")
        message(FATAL_ERROR "Library abort was not visible to CTest: ${output}")
    endif()
endforeach()
# Rebuilding without reconfiguring updates IDs and removes stale cases.
set(config Debug)
# Some Make versions compare source timestamps at whole-second precision.
run(0 "${CMAKE_COMMAND}" -E sleep 1.1)
file(READ "${WORK}/source fixture/cases.c" original_source)
file(WRITE "${WORK}/source fixture/cases.c" "#include \"baro.h\"\nTEST(\"[pass] newly added\") { CHECK(1); }\n\n\n${original_source}")
run(0 "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 4)
inventory(19)
foreach(index RANGE 0 17)
    string(JSON previous GET "${original}" tests ${index} name)
    math(EXPR shifted "${index} + 1")
    string(JSON current GET "${inventory}" tests ${shifted} name)
    if(NOT previous STREQUAL current)
        message(FATAL_ERROR "Insertion/line shifts changed identity: ${previous} -> ${current}")
    endif()
endforeach()
if(NOT inventory MATCHES "newly added")
    message(FATAL_ERROR "Added test was not discovered")
endif()
# Some Make versions compare source timestamps at whole-second precision.
run(0 "${CMAKE_COMMAND}" -E sleep 1.1)
file(WRITE "${WORK}/source fixture/cases.c" "${original_source}")
run(0 "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 4)
inventory(18)
if(inventory MATCHES "newly added")
    message(FATAL_ERROR "Removed test remains registered")
endif()
if(MULTI)
    set(config Release)
    inventory(18)
    run(0 "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C Release -L "^context$" --output-on-failure)
endif()
# A fresh checkout/build location must not leak absolute paths into test names.
set(prior_binary "${binary}")
file(COPY "${SOURCE}/tests/discovery_fixture/" DESTINATION "${WORK}/relocated source")
set(binary "${WORK}/relocated build")
run(0 "${CMAKE_COMMAND}" -S "${WORK}/relocated source" -B "${binary}" -G "${GENERATOR}"
    "-DBARO_SOURCE=${SOURCE}" -DCMAKE_BUILD_TYPE=Debug)
run(0 "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 4)
set(config Debug)
inventory(18)
foreach(index RANGE 0 17)
    string(JSON previous GET "${original}" tests ${index} name)
    string(JSON current GET "${inventory}" tests ${index} name)
    if(NOT previous STREQUAL current)
        message(FATAL_ERROR "Relocation changed identity: ${previous} -> ${current}")
    endif()
endforeach()
