function(run expected)
    execute_process(COMMAND "${PROGRAM}" --isolate ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: ${status}\n${out}${err}")
    endif()
    set(output "${out}" PARENT_SCOPE)
endfunction()
run(0 -t isolated_state)
if(NOT output MATCHES "2 total.*2 passed.*0 failed")
    message(FATAL_ERROR "Tests did not receive fresh process state: ${output}")
endif()
run(1 -t isolated_exit --junit "${WORK}/exit.xml")
if(NOT output MATCHES "Abnormal termination")
    message(FATAL_ERROR "Premature exit was accepted: ${output}")
endif()
run(1 -t abort)
if(NOT output MATCHES "3 total.*1 passed.*2 failed" OR NOT output MATCHES "SIGABRT")
    message(FATAL_ERROR "Abort did not preserve continuation: ${output}")
endif()
run(1 -t isolated_crash)
if(NOT output MATCHES "Abnormal termination|SIGABRT")
    message(FATAL_ERROR "Crash was accepted: ${output}")
endif()
run(0 --test "[numeric] original types and single evaluation")
run(0 -t isolated_state -n 2 -p 2)
if(NOT output MATCHES "1 total.*1 passed.*0 failed")
    message(FATAL_ERROR "Partition selected wrong tests: ${output}")
endif()
run(1 -t float_failure)
if(NOT output MATCHES "1.1 == 1.9")
    message(FATAL_ERROR "Missing child diagnostic: ${output}")
endif()
run(1 -t deadline --timeout 500ms --jobs 1)
if(NOT output MATCHES "Timeout" OR NOT output MATCHES "2 total.*1 passed.*1 failed")
    message(FATAL_ERROR "Timeout did not preserve continuation: ${output}")
endif()
run(1 -t stop -s)
if(NOT output MATCHES "1 total.*0 passed.*1 failed" OR output MATCHES "UNREACHABLE")
    message(FATAL_ERROR "Stop-after-failure started another test: ${output}")
endif()
run(0 -t expected_abort)
run(1 -t missing_abort)
if(NOT output MATCHES "Expected SIGABRT")
    message(FATAL_ERROR "Missing expected abort accepted: ${output}")
endif()
run(1 -t wrong_abort)
run(1 --jobs 0)
run(1 --timeout 0)
run(1 --timeout nonsense)
run(1 --recover-abort)
file(REMOVE_RECURSE "${WORK}/barrier")
file(MAKE_DIRECTORY "${WORK}/barrier")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "BARO_BARRIER_DIR=${WORK}/barrier"
    "${PROGRAM}" --isolate -t workers --jobs 4 --timeout 5s
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
if(NOT "${status}" STREQUAL "0" OR NOT out MATCHES "4 total.*4 passed.*0 failed")
    message(FATAL_ERROR "Workers were not concurrent: ${out}${err}")
endif()
run(1 -t abort_with_failure)
if(NOT output MATCHES "Assertions failed before SIGABRT")
    message(FATAL_ERROR "Expected abort hid assertion failure: ${output}")
endif()
file(REMOVE "${WORK}/descendant-marker" "${WORK}/descendant-marker.started")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "BARO_DESCENDANT_EXE=${DESCENDANT}"
    "BARO_DESCENDANT_MARKER=${WORK}/descendant-marker"
    "${PROGRAM}" --isolate -t descendants --timeout 750ms
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
if(NOT "${status}" STREQUAL "1" OR NOT out MATCHES "Timeout" OR NOT EXISTS "${WORK}/descendant-marker.started")
    message(FATAL_ERROR "Descendant did not start before timeout: ${out}${err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 2)
if(EXISTS "${WORK}/descendant-marker")
    message(FATAL_ERROR "Descendant survived the test timeout")
endif()
