# Generic comparisons print operand values only when the language mode allows it.
function(check expected)
    execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${status}" STREQUAL "${expected}" OR NOT "${err}" STREQUAL "")
        message(FATAL_ERROR "${ARGN}: ${status}\n${out}${err}")
    endif()
    string(REPLACE "\r\n" "\n" out "${out}")
    set(output "${out}" PARENT_SCOPE)
endfunction()
check(0 -t values_pass)
if(NOT output MATCHES "14 total.*14 passed.*0 failed")
    message(FATAL_ERROR "Comparison semantics changed: ${output}")
endif()
check(1 -t values_fail)
if(NOT output MATCHES "11 total.*0 passed.*11 failed")
    message(FATAL_ERROR "Unexpected totals: ${output}")
endif()
function(expect expression value)
    set(expected "    ${expression}\n")
    if(VALUES)
        string(APPEND expected "==> ${value}")
    else()
        string(APPEND expected "At ")
    endif()
    string(FIND "${output}" "${expected}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing '${expected}': ${output}")
    endif()
endfunction()
expect("x + 1 == 5" "4 == 5\n")
expect("2.5 < 1.5" "2.5 < 1.5\n")
expect("count >= 9u" "7 >= 9\n")
expect("-1L != -1L" "-1 != -1\n")
expect("large == 1" "18446744073709551615 == 1\n")
expect("letter == 'b'" "97 == 98\n")
expect("half > 1" "0.5 > 1\n")
expect("wide == 2.5L" "1.5 == 2.5\n")
expect("x == count" "3 == 7\n")
# Pointer formatting is platform-defined, but both addresses must be shown.
if(VALUES AND NOT output MATCHES "    &x == other\n==> [^ \n]+ == [^ \n]+\n")
    message(FATAL_ERROR "Missing pointer values: ${output}")
endif()
expect("x <= 2" "3 <= 2\n")
string(FIND "${output}" "Check failed: described\n" found)
if(found EQUAL -1)
    message(FATAL_ERROR "Missing description: ${output}")
endif()
if(NOT MSVC)
    check(0 -t values_extra_pass)
    if(NOT output MATCHES "5 total.*5 passed.*0 failed")
        message(FATAL_ERROR "Variably modified operands were not evaluated once: ${output}")
    endif()
    check(1 -t values_extra_fail)
    string(FIND "${output}" "    z == 2\nAt " found)
    if(found EQUAL -1)
        message(FATAL_ERROR "A complex operand must not be displayed: ${output}")
    endif()
endif()
