include_guard(GLOBAL)

# Literal quoting for generated parameter files. Generator expressions are
# expanded by file(GENERATE); ordinary ${variables} remain literal data.
function(_baro_literal out value)
    set(eq "=")
    while(TRUE)
        string(FIND "${value}" "]${eq}]" found)
        if(found EQUAL -1)
            break()
        endif()
        string(APPEND eq "=")
    endwhile()
    if(value MATCHES "^\n")
        string(PREPEND value "\n")
    endif()
    set(${out} "[${eq}[${value}]${eq}]" PARENT_SCOPE)
endfunction()

# Runtime code uses escaped quotes: bracket arguments normalize CRLF when read
# from generated files. Keep literals above for generator-expression parameters.
function(_baro_code_quote out value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "$" "\\$" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(baro_discover_tests target)
    cmake_parse_arguments(PARSE_ARGV 1 ARG ""
        "TEST_PREFIX;TEST_SUFFIX;WORKING_DIRECTORY;TIMEOUT;DISCOVERY_TIMEOUT;RUNNER"
        "ENVIRONMENT;LABELS;PROPERTIES;EXTRA_ARGS")
    # PARSE_ARGV before CMP0174 cannot distinguish an empty prefix from absence.
    foreach(key TEST_PREFIX TEST_SUFFIX)
        math(EXPR last_arg "${ARGC} - 1")
        foreach(index RANGE 1 ${last_arg})
            if("${ARGV${index}}" STREQUAL "${key}")
                math(EXPR value_index "${index} + 1")
                if(value_index LESS ARGC AND "${ARGV${value_index}}" STREQUAL "")
                    set(ARG_${key} "")
                    list(REMOVE_ITEM ARG_KEYWORDS_MISSING_VALUES "${key}")
                endif()
            endif()
        endforeach()
    endforeach()
    if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "baro_discover_tests: unknown arguments or missing values")
    endif()
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "baro_discover_tests: ${target} is not a target")
    endif()
    get_target_property(kind "${target}" TYPE)
    get_target_property(already "${target}" _BARO_DISCOVERED)
    if(NOT kind STREQUAL "EXECUTABLE" OR already)
        message(FATAL_ERROR "baro_discover_tests: call once per executable target")
    endif()
    list(LENGTH ARG_PROPERTIES properties_length)
    math(EXPR odd "${properties_length} % 2")
    if(odd)
        message(FATAL_ERROR "baro_discover_tests: PROPERTIES requires name/value pairs")
    endif()
    if(NOT DEFINED ARG_TEST_PREFIX)
        set(ARG_TEST_PREFIX "${target}::")
    endif()
    if(NOT DEFINED ARG_WORKING_DIRECTORY)
        set(ARG_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    endif()
    if(NOT IS_ABSOLUTE "${ARG_WORKING_DIRECTORY}" AND NOT ARG_WORKING_DIRECTORY MATCHES "\\$<")
        get_filename_component(ARG_WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
    endif()
    if(NOT DEFINED ARG_DISCOVERY_TIMEOUT)
        set(ARG_DISCOVERY_TIMEOUT 10)
    endif()
    foreach(key TIMEOUT DISCOVERY_TIMEOUT)
        if(DEFINED ARG_${key} AND NOT ARG_${key} MATCHES "^[0-9]+([.][0-9]+)?$")
            message(FATAL_ERROR "baro_discover_tests: ${key} must be nonnegative seconds")
        endif()
    endforeach()
    if(ARG_DISCOVERY_TIMEOUT LESS_EQUAL 0)
        message(FATAL_ERROR "baro_discover_tests: DISCOVERY_TIMEOUT must be positive")
    endif()
    # CTest owns concurrency and deadlines. Permit only output-related options.
    foreach(arg IN LISTS ARG_EXTRA_ARGS)
        if(NOT arg MATCHES "^-[aoe]+$")
            message(FATAL_ERROR "baro_discover_tests: EXTRA_ARGS only accepts -a/-o/-e (including clusters)")
        endif()
    endforeach()
    get_target_property(emulator "${target}" CROSSCOMPILING_EMULATOR)
    if(NOT emulator)
        set(emulator "")
    endif()
    if(CMAKE_CROSSCOMPILING AND NOT emulator)
        message(FATAL_ERROR "baro_discover_tests requires CROSSCOMPILING_EMULATOR for a cross-built executable")
    endif()
    if(NOT ARG_RUNNER)
        if(CMAKE_CROSSCOMPILING)
            message(FATAL_ERROR "Cross builds require RUNNER pointing to a host-built baro_ctest")
        endif()
        set(ARG_RUNNER "$<TARGET_FILE:baro::ctest>")
        add_dependencies("${target}" baro::ctest)
    endif()
    set_property(TARGET "${target}" PROPERTY _BARO_DISCOVERED TRUE)
    set(base "${CMAKE_CURRENT_BINARY_DIR}/.baro/${target}")
    file(MAKE_DIRECTORY "${base}")
    _baro_literal(cmake_command "${CMAKE_COMMAND}")
    _baro_literal(source_directory "${CMAKE_CURRENT_SOURCE_DIR}")
    set(content "set(BARO_SOURCE_DIRECTORY ${source_directory})\ncmake_policy(SET CMP0011 NEW)\nset(BARO_CMAKE_COMMAND ${cmake_command})\n")
    foreach(key TEST_PREFIX TEST_SUFFIX WORKING_DIRECTORY TIMEOUT DISCOVERY_TIMEOUT RUNNER)
        _baro_literal(value "${ARG_${key}}")
        string(APPEND content "set(BARO_${key} ${value})\n")
    endforeach()
    set(ARG_EMULATOR "${emulator}")
    foreach(key ENVIRONMENT LABELS PROPERTIES EXTRA_ARGS EMULATOR)
        set(index 0)
        foreach(item IN LISTS ARG_${key})
            _baro_literal(value "${item}")
            string(APPEND content "set(BARO_${key}_${index} ${value})\n")
            math(EXPR index "${index} + 1")
        endforeach()
        string(APPEND content "set(BARO_${key}_COUNT ${index})\n")
    endforeach()
    _baro_literal(executable "$<TARGET_FILE:${target}>")
    _baro_literal(output "${base}/$<CONFIG>.tests.cmake")
    _baro_literal(manifest "${base}/$<CONFIG>.json")
    _baro_literal(implementation "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/BaroDiscoverTests.cmake")
    string(APPEND content "set(BARO_EXECUTABLE ${executable})\nset(BARO_OUTPUT ${output})\nset(BARO_MANIFEST ${manifest})\ninclude(${implementation})\n")
    file(GENERATE OUTPUT "${base}/$<CONFIG>.include.cmake" CONTENT "${content}" TARGET "${target}")
    get_property(multi GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(multi)
        _baro_literal(configs "${CMAKE_CONFIGURATION_TYPES}")
        _baro_literal(base_quoted "${base}")
        file(WRITE "${base}/include.cmake"
            "set(_baro_configs ${configs})\nset(_baro_base ${base_quoted})\n"
            "list(FIND _baro_configs \"\${CTEST_CONFIGURATION_TYPE}\" _baro_config_index)\nif(_baro_config_index LESS 0)\n  message(FATAL_ERROR \"Specify a built configuration with ctest -C <config>\")\nendif()\n"
            "include(\"\${_baro_base}/\${CTEST_CONFIGURATION_TYPE}.include.cmake\")\n")
    else()
        _baro_literal(include_file "${base}/${CMAKE_BUILD_TYPE}.include.cmake")
        file(WRITE "${base}/include.cmake" "include(${include_file})\n")
    endif()
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${base}/include.cmake")
endfunction()
